services:
  - type: web
    name: lingualab-translator
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.translate
    healthCheckPath: /languages
    envVars:
      - key: LT_LOAD_ONLY
        value: en,de
      - key: LT_HOST
        value: 0.0.0.0
      - key: LT_PORT
        value: 10000
      - key: LT_DISABLE_WEB_UI
        value: "true"
