import type { Exercise, Topic } from './data'

const gap = (before: string, answer: string, after: string, hint: string): Exercise => ({ before, answer, after, hint })

export const extendedCatalogTopics: Topic[] = [
  {
    name: 'Prepositions of Place', level: 'A1', category: 'Präpositionen',
    summary: 'Ortspräpositionen beschreiben, wo sich Personen und Dinge befinden.',
    structure: 'in, on, under, next to, between, behind, in front of',
    usage: ['Positionen im Raum beschreiben', 'in für innerhalb', 'on für auf einer Oberfläche'],
    signalWords: ['in', 'on', 'under', 'next to', 'between', 'behind'],
    examples: ['The keys are on the table.', 'The cat is under the chair.', 'The bank is next to the café.'],
    exercises: [
      gap('The milk is ', 'in', ' the fridge.', 'in/on'), gap('Your phone is ', 'on', ' the desk.', 'in/on'),
      gap('The cat is hiding ', 'under', ' the bed.', 'unter'), gap('The pharmacy is ', 'next to', ' the bank.', 'neben'),
      gap('Mia is standing ', 'between', ' Tom and Leo.', 'zwischen'), gap('The garden is ', 'behind', ' the house.', 'hinter'),
      gap('There is a bus stop ', 'in front of', ' the school.', 'vor'), gap('The picture is ', 'on', ' the wall.', 'in/on'),
      gap('The children are ', 'in', ' the classroom.', 'in/on'), gap('My shoes are ', 'under', ' the chair.', 'unter'),
    ],
  },
  {
    name: 'Question Words', level: 'A1', category: 'Fragen',
    summary: 'Fragewörter helfen, gezielt nach Personen, Orten, Zeiten, Gründen und Dingen zu fragen.',
    structure: 'question word + auxiliary + subject + verb',
    usage: ['who für Personen', 'where für Orte', 'when für Zeiten', 'why für Gründe'],
    signalWords: ['who', 'what', 'where', 'when', 'why', 'how'],
    examples: ['Where do you live?', 'Who is your teacher?', 'Why are you late?'],
    exercises: [
      gap('', 'Where', ' do you live?', 'Ort'), gap('', 'Who', ' is that man?', 'Person'),
      gap('', 'When', ' does the film start?', 'Zeit'), gap('', 'Why', ' are you tired?', 'Grund'),
      gap('', 'What', ' is your name?', 'Sache'), gap('', 'How', ' do you go to school?', 'Art und Weise'),
      gap('', 'Which', ' colour do you prefer?', 'Auswahl'), gap('', 'How old', ' is your sister?', 'Alter'),
      gap('', 'Whose', ' bag is this?', 'Besitz'), gap('', 'How many', ' brothers have you got?', 'Anzahl'),
    ],
  },
  {
    name: 'There is and There are', level: 'A1', category: 'Satzbau',
    summary: 'There is und there are sagen aus, dass etwas vorhanden ist oder sich irgendwo befindet.',
    structure: 'there is + Singular · there are + Plural',
    usage: ['Dinge und Orte beschreiben', 'Singular und Plural unterscheiden', 'Fragen und Verneinungen bilden'],
    signalWords: ['there is', 'there are', 'is there', 'are there'],
    examples: ['There is a park nearby.', 'There are two cafés.', 'Is there a station?'],
    exercises: [
      gap('', 'There is', ' a book on the table.', 'Singular'), gap('', 'There are', ' three windows.', 'Plural'),
      gap('', 'Is there', ' a bank near here?', 'Frage Singular'), gap('', 'Are there', ' any questions?', 'Frage Plural'),
      gap('There ', 'isn’t', ' a lift in the building.', 'not Singular'), gap('There ', 'aren’t', ' any clean cups.', 'not Plural'),
      gap('', 'There is', ' some milk in the fridge.', 'Singular'), gap('', 'There are', ' many people outside.', 'Plural'),
      gap('', 'Is there', ' enough time?', 'Frage Singular'), gap('', 'There are', ' two messages for you.', 'Plural'),
    ],
  },
  {
    name: 'Prepositions of Time', level: 'A2', category: 'Präpositionen',
    summary: 'Zeitpräpositionen ordnen Zeitpunkte, Zeiträume, Beginn und Ende einer Handlung ein.',
    structure: 'at + Uhrzeit · on + Tag · in + Monat/Jahr · since/for/until + Zeitraum',
    usage: ['at für genaue Uhrzeiten', 'on für Tage und Daten', 'in für Monate und Jahre', 'since, for und until für Zeiträume'],
    signalWords: ['at', 'on', 'in', 'since', 'for', 'until'],
    examples: ['We meet at six.', 'She arrived on Monday.', 'I have lived here since 2020.'],
    exercises: [
      gap('The lesson starts ', 'at', ' nine o’clock.', 'at/in/on'), gap('We visit them ', 'on', ' Sundays.', 'at/in/on'),
      gap('My birthday is ', 'in', ' July.', 'at/in/on'), gap('She has worked here ', 'since', ' 2021.', 'since/for'),
      gap('They stayed in York ', 'for', ' two weeks.', 'since/for'), gap('I will wait ', 'until', ' six o’clock.', 'bis'),
      gap('The office is closed ', 'at', ' lunchtime.', 'at/in/on'), gap('We moved here ', 'in', ' 2019.', 'at/in/on'),
      gap('The meeting is ', 'on', ' 12 May.', 'at/in/on'), gap('He studied ', 'from', ' Monday until Friday.', 'von'),
    ],
  },
  {
    name: 'Past Progressive', level: 'A2', category: 'Zeitformen',
    summary: 'Das Past Progressive beschreibt Handlungen, die zu einem Zeitpunkt in der Vergangenheit gerade liefen.',
    structure: 'was/were + Verb-ing',
    usage: ['Laufende vergangene Handlungen', 'Hintergrund einer Erzählung', 'Unterbrochene Handlungen mit when'],
    signalWords: ['while', 'when', 'at five yesterday', 'all evening'],
    examples: ['I was reading at eight.', 'They were sleeping when I called.', 'While she was cooking, he arrived.'],
    exercises: [
      gap('I ', 'was reading', ' when you called.', 'read'), gap('They ', 'were playing', ' football at five.', 'play'),
      gap('Mia ', 'was cooking', ' while Tom set the table.', 'cook'), gap('We ', 'were waiting', ' for the bus.', 'wait'),
      gap('It ', 'was raining', ' all morning.', 'rain'), gap('You ', 'were sleeping', ' when I came home.', 'sleep'),
      gap('The children ', 'were watching', ' a film.', 'watch'), gap('Leo ', 'was driving', ' to work at seven.', 'drive'),
      gap('I ', 'wasn’t listening', ' during the lesson.', 'not listen'), gap('What ', 'were you doing', ' at midnight?', 'you/do'),
    ],
  },
  {
    name: 'Quantifiers', level: 'A2', category: 'Mengenangaben',
    summary: 'Mengenwörter unterscheiden zählbare und nicht zählbare Nomen.',
    structure: 'many/few + countable · much/little + uncountable · some/any + beide',
    usage: ['Mengen genau oder ungenau angeben', 'Zählbare Nomen erkennen', 'Fragen und Verneinungen mit any bilden'],
    signalWords: ['some', 'any', 'much', 'many', 'few', 'little'],
    examples: ['We have some time.', 'How many books are there?', 'There isn’t much milk.'],
    exercises: [
      gap('There are ', 'many', ' students here.', 'zählbar'), gap('We don’t have ', 'much', ' time.', 'nicht zählbar'),
      gap('I need ', 'some', ' information.', 'positive Aussage'), gap('Are there ', 'any', ' questions?', 'Frage'),
      gap('Only a ', 'few', ' people came.', 'zählbar, wenig'), gap('There is very ', 'little', ' water left.', 'nicht zählbar, wenig'),
      gap('How ', 'many', ' emails did you send?', 'zählbar'), gap('How ', 'much', ' money do we need?', 'nicht zählbar'),
      gap('She bought ', 'some', ' apples.', 'positive Aussage'), gap('I haven’t got ', 'any', ' luggage.', 'Verneinung'),
    ],
  },
  {
    name: 'Must, Have to and Should', level: 'A2', category: 'Modalverben',
    summary: 'Diese Modalformen drücken Pflichten, Regeln, Notwendigkeiten und Ratschläge aus.',
    structure: 'must/have to/should + Grundform',
    usage: ['must für starke persönliche Pflicht', 'have to für äußere Regeln', 'should für Empfehlungen'],
    signalWords: ['must', 'mustn’t', 'have to', 'don’t have to', 'should'],
    examples: ['You must be careful.', 'We have to wear uniforms.', 'You should rest.'],
    exercises: [
      gap('You ', 'mustn’t', ' smoke here.', 'Verbot'), gap('I ', 'have to', ' get up early for work.', 'äußere Pflicht'),
      gap('You ', 'should', ' drink more water.', 'Ratschlag'), gap('Visitors ', 'must', ' show their ID.', 'starke Regel'),
      gap('We ', 'don’t have to', ' work on Sunday.', 'nicht notwendig'), gap('She ', 'has to', ' take the bus.', 'äußere Pflicht'),
      gap('You ', 'shouldn’t', ' stay up so late.', 'negativer Ratschlag'), gap('I ', 'must', ' remember to call Mia.', 'persönliche Pflicht'),
      gap('Do we ', 'have to', ' book in advance?', 'Notwendigkeit'), gap('Employees ', 'mustn’t', ' share passwords.', 'Verbot'),
    ],
  },
  {
    name: 'Present Perfect or Simple Past', level: 'B1', category: 'Zeitformen',
    summary: 'Simple Past nennt einen abgeschlossenen Zeitpunkt; Present Perfect betont Erfahrung oder Gegenwartsbezug.',
    structure: 'Simple Past: Verb-ed/2. Form · Present Perfect: have/has + participle',
    usage: ['Simple Past mit abgeschlossenem Zeitpunkt', 'Present Perfect ohne genaue Zeitangabe', 'since und for mit Present Perfect'],
    signalWords: ['yesterday', 'last year', 'ever', 'never', 'since', 'yet'],
    examples: ['I saw her yesterday.', 'I have seen that film.', 'She has lived here since May.'],
    exercises: [
      gap('I ', 'visited', ' Dublin last year.', 'visit'), gap('Have you ever ', 'been', ' to Dublin?', 'be'),
      gap('She ', 'has worked', ' here since May.', 'work'), gap('We ', 'finished', ' the project yesterday.', 'finish'),
      gap('Tom hasn’t ', 'called', ' yet.', 'call'), gap('They ', 'moved', ' to Bristol in 2022.', 'move'),
      gap('I ', 'have never eaten', ' octopus.', 'never eat'), gap('When ', 'did you meet', ' Mia?', 'you/meet'),
      gap('The train ', 'has just arrived', '.', 'just arrive'), gap('He ', 'lost', ' his keys two days ago.', 'lose'),
    ],
  },
  {
    name: 'Reported Speech', level: 'B1', category: 'Indirekte Rede',
    summary: 'Die indirekte Rede gibt Aussagen anderer Personen wieder, häufig mit einer Zeitverschiebung.',
    structure: 'said (that) + backshift · told + person + backshift',
    usage: ['Aussagen sinngemäß wiedergeben', 'Pronomen und Zeitangaben anpassen', 'said und told unterscheiden'],
    signalWords: ['said', 'told', 'that', 'the day before'],
    examples: ['“I am tired.” → She said she was tired.', 'He told me he would call.', 'Mia said she had finished.'],
    exercises: [
      gap('“I am busy.” She said she ', 'was', ' busy.', 'be'), gap('“We will call.” They said they ', 'would call', '.', 'call'),
      gap('“I like tea.” Tom said he ', 'liked', ' tea.', 'like'), gap('“I have finished.” Mia said she ', 'had finished', '.', 'finish'),
      gap('Leo ', 'told', ' me he was late.', 'say/tell'), gap('“I can swim.” She said she ', 'could swim', '.', 'swim'),
      gap('“We saw him.” They said they ', 'had seen', ' him.', 'see'), gap('Anna said ', 'that', ' she needed help.', 'Verbindungswort'),
      gap('“I’ll be there.” He ', 'promised', ' he would be there.', 'promise'), gap('She told us she ', 'didn’t know', ' the answer.', 'not know'),
    ],
  },
  {
    name: 'Used to', level: 'B1', category: 'Vergangenheit',
    summary: 'Used to beschreibt frühere Gewohnheiten oder Zustände, die heute nicht mehr gelten.',
    structure: 'used to + Grundform · didn’t use to · Did ... use to?',
    usage: ['Vergangene Gewohnheiten', 'Frühere Zustände', 'Kontrast zwischen früher und heute'],
    signalWords: ['used to', 'didn’t use to', 'when I was young', 'in the past'],
    examples: ['I used to play tennis.', 'She didn’t use to like coffee.', 'Did you use to live here?'],
    exercises: [
      gap('I ', 'used to walk', ' to school.', 'walk'), gap('She ', 'didn’t use to eat', ' vegetables.', 'not eat'),
      gap('Did you ', 'use to live', ' in York?', 'live'), gap('We ', 'used to visit', ' them every summer.', 'visit'),
      gap('This building ', 'used to be', ' a hospital.', 'be'), gap('Tom ', 'didn’t use to wear', ' glasses.', 'not wear'),
      gap('My parents ', 'used to travel', ' a lot.', 'travel'), gap('Did Mia ', 'use to work', ' here?', 'work'),
      gap('There ', 'used to be', ' a cinema here.', 'be'), gap('I ', 'used to believe', ' that story.', 'believe'),
    ],
  },
  {
    name: 'Gerund or Infinitive', level: 'B1', category: 'Verbformen',
    summary: 'Bestimmte Verben werden mit der ing-Form, andere mit dem Infinitiv mit to verbunden.',
    structure: 'enjoy/avoid + -ing · want/decide + to-infinitive',
    usage: ['Gerundium nach bestimmten Verben', 'Infinitiv nach Absichten und Entscheidungen', 'Feste Verbmuster lernen'],
    signalWords: ['enjoy doing', 'avoid doing', 'want to do', 'decide to do'],
    examples: ['I enjoy reading.', 'She decided to leave.', 'We avoid driving at night.'],
    exercises: [
      gap('I enjoy ', 'reading', ' in the evening.', 'read'), gap('She decided ', 'to apply', ' for the job.', 'apply'),
      gap('We avoid ', 'driving', ' during rush hour.', 'drive'), gap('Tom wants ', 'to learn', ' Spanish.', 'learn'),
      gap('They finished ', 'painting', ' the room.', 'paint'), gap('Mia promised ', 'to call', ' later.', 'call'),
      gap('Do you mind ', 'waiting', ' a moment?', 'wait'), gap('He hopes ', 'to study', ' abroad.', 'study'),
      gap('I suggested ', 'taking', ' the train.', 'take'), gap('She refused ', 'to answer', ' the question.', 'answer'),
    ],
  },
  {
    name: 'Third Conditional', level: 'B2', category: 'Bedingungssätze',
    summary: 'Der Third Conditional beschreibt irreale vergangene Bedingungen und deren nicht eingetretene Folgen.',
    structure: 'If + Past Perfect, would have + past participle',
    usage: ['Vergangene Situationen hypothetisch betrachten', 'Bedauern ausdrücken', 'Alternative Folgen formulieren'],
    signalWords: ['if', 'would have', 'could have', 'had'],
    examples: ['If I had known, I would have helped.', 'She would have come if you had invited her.', 'If we had left earlier, we wouldn’t have missed it.'],
    exercises: [
      gap('If I had known, I ', 'would have helped', ' you.', 'help'), gap('She would have come if you ', 'had invited', ' her.', 'invite'),
      gap('If we had left earlier, we ', 'wouldn’t have missed', ' the train.', 'not miss'), gap('They ', 'could have won', ' if they had trained more.', 'can win'),
      gap('If he ', 'had listened', ' to the advice, this wouldn’t have happened.', 'listen'), gap('I would have called if my phone ', 'had worked', '.', 'work'),
      gap('If you had told me, I ', 'would have understood', '.', 'understand'), gap('We wouldn’t have got lost if we ', 'had brought', ' a map.', 'bring'),
      gap('Would she have accepted if they ', 'had offered', ' more?', 'offer'), gap('If the weather had been better, we ', 'would have stayed', ' longer.', 'stay'),
    ],
  },
  {
    name: 'Modal Verbs of Deduction', level: 'B2', category: 'Modalverben',
    summary: 'Modalverben der Schlussfolgerung drücken aus, wie sicher eine Vermutung ist.',
    structure: 'must/might/can’t + Grundform · Vergangenheit: modal + have + participle',
    usage: ['Sichere Schlussfolgerungen mit must', 'Möglichkeiten mit might oder could', 'Unmögliches mit can’t ausschließen'],
    signalWords: ['must be', 'might be', 'can’t be', 'must have', 'might have'],
    examples: ['She must be tired.', 'He might have forgotten.', 'That can’t be true.'],
    exercises: [
      gap('The lights are off. They ', 'must be', ' asleep.', 'sicher'), gap('He isn’t answering. He ', 'might be', ' busy.', 'möglich'),
      gap('That story ', 'can’t be', ' true.', 'unmöglich'), gap('Mia knew everything. She ', 'must have read', ' the email.', 'read'),
      gap('They are late. They ', 'might have missed', ' the bus.', 'miss'), gap('Tom was abroad, so he ', 'can’t have attended', ' the meeting.', 'attend'),
      gap('This key ', 'could belong', ' to Anna.', 'belong'), gap('You worked all night. You ', 'must be', ' exhausted.', 'sicher'),
      gap('I’m not sure, but she ', 'may have left', ' early.', 'leave'), gap('He got full marks. The test ', 'can’t have been', ' difficult for him.', 'be'),
    ],
  },
  {
    name: 'Wish and If Only', level: 'B2', category: 'Satzbau',
    summary: 'Wish und if only drücken Wünsche, Bedauern und Unzufriedenheit mit gegenwärtigen oder vergangenen Situationen aus.',
    structure: 'wish + Past Simple · wish + Past Perfect · wish + would',
    usage: ['Irreale Wünsche in der Gegenwart', 'Bedauern über die Vergangenheit', 'Kritik an veränderbarem Verhalten'],
    signalWords: ['I wish', 'if only', 'would', 'had'],
    examples: ['I wish I had more time.', 'If only we had left earlier.', 'I wish he would listen.'],
    exercises: [
      gap('I wish I ', 'had', ' more free time.', 'have'), gap('If only we ', 'had booked', ' earlier.', 'book'),
      gap('She wishes she ', 'could speak', ' French.', 'can speak'), gap('I wish he ', 'would stop', ' interrupting.', 'stop'),
      gap('They wish they ', 'lived', ' closer to the city.', 'live'), gap('If only I ', 'hadn’t forgotten', ' her birthday.', 'not forget'),
      gap('Tom wishes the weather ', 'were', ' warmer.', 'be'), gap('I wish you ', 'wouldn’t leave', ' the door open.', 'not leave'),
      gap('We wish we ', 'had taken', ' more photos.', 'take'), gap('If only this computer ', 'worked', ' properly.', 'work'),
    ],
  },
  {
    name: 'Have Something Done', level: 'B2', category: 'Satzbau',
    summary: 'Die Kausativkonstruktion zeigt, dass eine andere Person eine Dienstleistung für das Subjekt ausführt.',
    structure: 'have/get + object + past participle',
    usage: ['Dienstleistungen beschreiben', 'Den Ausführenden nicht nennen', 'Verschiedene Zeitformen mit have bilden'],
    signalWords: ['have repaired', 'get cut', 'had delivered', 'will have installed'],
    examples: ['I had my hair cut.', 'We are having the roof repaired.', 'She will get her phone fixed.'],
    exercises: [
      gap('I ', 'had my hair cut', ' yesterday.', 'hair/cut'), gap('We are ', 'having the kitchen painted', ' this week.', 'kitchen/paint'),
      gap('She needs to ', 'get her phone repaired', '.', 'phone/repair'), gap('They ', 'had the documents translated', ' into English.', 'documents/translate'),
      gap('I will ', 'have the package delivered', ' tomorrow.', 'package/deliver'), gap('Tom ', 'has his car serviced', ' every year.', 'car/service'),
      gap('We should ', 'get the locks changed', '.', 'locks/change'), gap('Mia ', 'is having her eyes tested', ' today.', 'eyes/test'),
      gap('He ', 'had his passport stolen', ' while travelling.', 'passport/steal'), gap('By Friday, they will ', 'have the software installed', '.', 'software/install'),
    ],
  },
  {
    name: 'No-Go: Deutsche Direktübersetzungen', level: 'B1', category: 'Natürliche Kommunikation',
    summary: 'Viele deutsche Sätze lassen sich zwar Wort für Wort übersetzen, klingen im Englischen aber unnatürlich. Lerne die Formulierungen, die Muttersprachler wirklich verwenden.',
    structure: 'Deutschen Gedanken verstehen -> passende englische Wendung wählen',
    usage: ['Typische Germanismen vermeiden', 'Im Alltag natürlicher klingen', 'Feste englische Wendungen als Ganzes lernen'],
    signalWords: ['make sense', 'fingers crossed', 'feel like', 'get back to you', 'it’s on me'],
    examples: ['That makes sense. (nicht: That makes senseful.)', 'Fingers crossed! (nicht: I press my thumbs for you.)', 'I’ll get back to you. (nicht: I report myself.)'],
    exercises: [
      gap('„Das macht Sinn.“: That ', 'makes sense', '.', 'make sense'),
      gap('„Ich drücke dir die Daumen.“: ', 'Fingers crossed', '!', 'fingers crossed'),
      gap('„Ich habe Lust auf Pizza.“: I ', 'feel like pizza', '.', 'feel like'),
      gap('„Das geht auf mich.“: ', 'It’s on me|It is on me', '.', 'it’s on me'),
      gap('„Mach dir keinen Kopf.“: ', 'Don’t worry about it|Do not worry about it', '.', 'don’t worry'),
      gap('„Ich melde mich bei dir.“: I ', 'will get back to you|I’ll get back to you', '.', 'get back to you'),
      gap('„Ich gehe nach Hause.“: I ', 'am going home|I’m going home', '.', 'go home'),
      gap('„Ich bin fertig.“: I ', 'am done|I’m done', '.', 'be done'),
      gap('„Seit wann lernst du Englisch?“: How long ', 'have you been learning English', '?', 'present perfect progressive'),
      gap('„Ich bekomme ein Kind.“: I ', 'am having a baby|I’m having a baby', '.', 'have a baby'),
    ],
  },
  {
    name: 'Small Talk im Alltag', level: 'A2', category: 'Kommunikation',
    summary: 'Small Talk eröffnet kurze, freundliche Gespräche. Im Englischen helfen offene Fragen und kleine Reaktionen, statt nur mit ja oder nein zu antworten.',
    structure: 'offene Frage + kurze Reaktion + Rückfrage',
    usage: ['Gespräche beginnen', 'Auf Wetter, Arbeit oder Pläne reagieren', 'Interesse mit einer Rückfrage zeigen'],
    signalWords: ['How are things?', 'How was your weekend?', 'Really?', 'What about you?'],
    examples: ['How was your weekend? Pretty good, thanks. What about you?', 'Lovely weather today, isn’t it?', 'I see what you mean.'],
    exercises: [
      gap('„Wie war dein Wochenende?“: How ', 'was your weekend', '?', 'weekend'),
      gap('„Und bei dir?“: What ', 'about you', '?', 'about you'),
      gap('„Das klingt gut.“: That ', 'sounds good', '.', 'sound good'),
      gap('„Wirklich?“: ', 'Really', '?', 'really'),
      gap('„Schönes Wetter heute, oder?“: Lovely weather today, ', 'isn’t it', '?', 'question tag'),
      gap('„Was machst du beruflich?“: What do you ', 'do', '?', 'do'),
      gap('„Ich verstehe, was du meinst.“: I ', 'see what you mean', '.', 'see what you mean'),
      gap('„Wie läuft es?“: How are ', 'things', '?', 'things'),
      gap('„Das ist interessant.“: That’s ', 'interesting|That is interesting', '.', 'interesting'),
      gap('„Bis bald.“: See you ', 'soon', '.', 'soon'),
    ],
  },
  {
    name: 'Höflich bitten und ablehnen', level: 'B1', category: 'Kommunikation',
    summary: 'Im Englischen wirken Bitten und Absagen meist indirekter als im Deutschen. Modalverben und freundliche Einleitungen machen Aussagen angemessen.',
    structure: 'Could/Would + subject + possibly ...? · I’m afraid ... · Would you mind ...?',
    usage: ['Freundlich um Hilfe bitten', 'Eine Bitte höflich ablehnen', 'Unterbrechungen und Wünsche abschwächen'],
    signalWords: ['could you', 'would you mind', 'I’m afraid', 'I was wondering if', 'sorry, but'],
    examples: ['Could you possibly help me?', 'Would you mind closing the window?', 'I’m afraid I can’t make it.'],
    exercises: [
      gap('„Könntest du mir bitte helfen?“: Could you ', 'possibly help me', '?', 'possibly help'),
      gap('„Würde es dir etwas ausmachen, das Fenster zu schließen?“: Would you mind ', 'closing the window', '?', 'close'),
      gap('„Leider kann ich es nicht schaffen.“: I’m afraid I ', 'can’t make it|cannot make it', '.', 'can’t make it'),
      gap('„Ich wollte fragen, ob ...“: I ', 'was wondering if', ' you could help.', 'wonder'),
      gap('„Entschuldigung, aber ich bin beschäftigt.“: I’m sorry, but I’m ', 'busy', '.', 'busy'),
      gap('„Könnten Sie das wiederholen?“: Could you ', 'repeat that', ', please?', 'repeat'),
      gap('„Leider habe ich keine Zeit.“: Unfortunately, I ', 'don’t have time|do not have time', '.', 'not have time'),
      gap('„Wäre es möglich, später zu kommen?“: Would it ', 'be possible', ' to come later?', 'possible'),
      gap('„Ich würde lieber nicht.“: I’d ', 'rather not|would rather not', '.', 'rather not'),
      gap('„Kein Problem.“: No ', 'problem', '.', 'problem'),
    ],
  },
  {
    name: 'Telefonieren und E-Mails', level: 'B1', category: 'Kommunikation',
    summary: 'Am Telefon und in E-Mails helfen feste Wendungen, damit du Anliegen klar, höflich und professionell formulierst.',
    structure: 'This is ... speaking · I’m calling about ... · Could you let me know ...?',
    usage: ['Sich am Telefon melden', 'Nachfragen und Nachrichten hinterlassen', 'Freundliche E-Mails beginnen und beenden'],
    signalWords: ['speaking', 'calling about', 'put through', 'get back to', 'kind regards'],
    examples: ['Hello, this is Anna speaking.', 'Could you put me through to Mr Brown?', 'Kind regards, Lena'],
    exercises: [
      gap('„Hallo, hier ist Anna.“: Hello, this is Anna ', 'speaking', '.', 'speaking'),
      gap('„Ich rufe wegen Ihrer Bestellung an.“: I’m calling ', 'about your order', '.', 'about'),
      gap('„Könnten Sie mich zu Frau Brown durchstellen?“: Could you put me ', 'through to Mrs Brown', '?', 'put through'),
      gap('„Kann ich eine Nachricht hinterlassen?“: Can I ', 'leave a message', '?', 'leave message'),
      gap('„Könnten Sie mir Bescheid geben?“: Could you ', 'let me know', '?', 'let me know'),
      gap('„Vielen Dank im Voraus.“: Thank you ', 'in advance', '.', 'in advance'),
      gap('„Mit freundlichen Grüßen“: Kind ', 'regards', ',', 'regards'),
      gap('„Anbei finden Sie ...“: Please find ', 'attached', ' the document.', 'attached'),
      gap('„Entschuldigen Sie die späte Antwort.“: Sorry for the ', 'late reply', '.', 'late reply'),
      gap('„Ich freue mich auf Ihre Antwort.“: I look forward to ', 'hearing from you', '.', 'hear from you'),
    ],
  },
  {
    name: 'False Friends für Deutsche', level: 'B1', category: 'Wortschatz',
    summary: 'False Friends sehen deutschen Wörtern ähnlich, haben im Englischen aber eine andere Bedeutung. Sie führen schnell zu Missverständnissen.',
    structure: 'ähnliches Wort erkennen -> tatsächliche Bedeutung prüfen -> passendes englisches Wort wählen',
    usage: ['Typische Verwechslungen vermeiden', 'Wortschatz präziser einsetzen', 'Missverständnisse im Alltag vermeiden'],
    signalWords: ['actual', 'eventually', 'chef', 'become', 'sensible'],
    examples: ['Actually means „eigentlich“, not „aktuell“.', 'Eventually means „schließlich“, not „eventuell“.', 'A chef cooks professionally; a boss is a chef in German.'],
    exercises: [
      gap('„aktuell“ heißt meistens ', 'current|currently', ', nicht actual.', 'current'),
      gap('„eigentlich“ heißt ', 'actually', ', nicht actual.', 'actually'),
      gap('„eventuell“ heißt ', 'possibly|perhaps|maybe', ', nicht eventually.', 'possibly'),
      gap('„schließlich“ heißt ', 'eventually', ', nicht possibly.', 'eventually'),
      gap('„Chef“ im Büro heißt ', 'boss|manager', ', nicht chef.', 'boss'),
      gap('„bekommen“ heißt oft ', 'get|receive', ', nicht become.', 'get'),
      gap('„vernünftig“ heißt ', 'sensible', ', nicht sensitive.', 'sensible'),
      gap('„sensibel“ heißt ', 'sensitive', ', nicht sensible.', 'sensitive'),
      gap('„Gymnasium“ heißt ', 'secondary school|high school', ', nicht gymnasium.', 'school'),
      gap('„Kontrolle“ heißt in vielen Situationen ', 'check', ', nicht control.', 'check'),
    ],
  },
  {
    name: 'Aussprachefallen für Deutsche', level: 'B1', category: 'Aussprache',
    summary: 'Einige englische Laute und Betonungen gibt es im Deutschen nicht. Kleine Unterschiede verändern oft die Bedeutung eines Wortes.',
    structure: 'Laut bewusst hören -> Mundstellung nachahmen -> Wort in einem Satz verwenden',
    usage: ['Kurze und lange Vokale unterscheiden', 'th-Laute trainieren', 'Stumme Buchstaben und Wortbetonung beachten'],
    signalWords: ['ship/sheep', 'think/this', 'three/tree', 'listen', 'comfortable'],
    examples: ['ship / sheep: Der lange Vokal in sheep ist deutlich länger.', 'think beginnt mit dem stimmlosen th-Laut.', 'The t in listen is silent.'],
    exercises: [
      gap('Das Wort für „Schiff“ ist ', 'ship', ', nicht sheep.', 'short i'),
      gap('Das Wort für „Schaf“ ist ', 'sheep', ', nicht ship.', 'long ee'),
      gap('„denken“ heißt ', 'think', ' und beginnt mit th.', 'think'),
      gap('„dies“ heißt ', 'this', ' und beginnt mit stimmhaftem th.', 'this'),
      gap('In „listen“ ist das ', 't', ' stumm.', 'silent letter'),
      gap('„drei“ heißt ', 'three', ', nicht tree.', 'three'),
      gap('Die Betonung in „comfortable“ liegt auf der ersten Silbe: ', 'COMfortable', '.', 'stress'),
      gap('„Welt“ heißt ', 'world', ', nicht word.', 'world'),
      gap('„Arbeit“ heißt ', 'work', ', nicht walk.', 'work'),
      gap('„Strand“ heißt ', 'beach', ', nicht bitch.', 'long ee'),
    ],
  },
  {
    name: 'To Be und Have Got', level: 'A1', category: 'Grundlagen',
    summary: 'To be beschreibt Identität, Eigenschaften und Zustände. Have got drückt Besitz und Zugehörigkeit aus.',
    structure: 'be: am/is/are · have got: have/has got · Fragen: be/have vor dem Subjekt',
    usage: ['Sich und andere vorstellen', 'Eigenschaften und Orte beschreiben', 'Besitz und Familie nennen'],
    signalWords: ['am', 'is', 'are', 'have got', 'has got', 'isn’t'],
    examples: ['I am from Berlin.', 'She is tired.', 'We have got two cats.'],
    exercises: [
      gap('I ', 'am', ' from Germany.', 'be'), gap('My sister ', 'is', ' a teacher.', 'be'),
      gap('We ', 'are', ' ready.', 'be'), gap('He ', 'has got', ' a new bike.', 'have got'),
      gap('They ', 'have got', ' a small garden.', 'have got'), gap('She ', 'isn’t|is not', ' at home.', 'not be'),
      gap('I ', 'haven’t got|have not got', ' any brothers.', 'not have got'), gap('', 'Are', ' you hungry?', 'question be'),
      gap('', 'Has', ' he got a dog?', 'question have got'), gap('My friends ', 'are', ' in the kitchen.', 'be'),
    ],
  },
  {
    name: 'Fragen und Verneinungen mit Do', level: 'A1', category: 'Grundlagen',
    summary: 'Bei den meisten Verben bilden do, does und did Fragen und Verneinungen. Das Hauptverb bleibt dann in der Grundform.',
    structure: 'do/does/did + subject + base verb · subject + do/does/did not + base verb',
    usage: ['Fragen im Simple Present und Simple Past bilden', 'Gewohnheiten und vergangene Handlungen verneinen', 'Die Grundform nach dem Hilfsverb verwenden'],
    signalWords: ['do', 'does', 'did', 'don’t', 'doesn’t', 'didn’t'],
    examples: ['Do you live here?', 'She doesn’t like coffee.', 'Did they call yesterday?'],
    exercises: [
      gap('', 'Do', ' you speak English?', 'question present'), gap('', 'Does', ' Mia work here?', 'question present'),
      gap('I ', 'don’t like|do not like', ' cold weather.', 'not like'), gap('He ', 'doesn’t play|does not play', ' tennis.', 'not play'),
      gap('', 'Did', ' you see the film?', 'question past'), gap('We ', 'didn’t go|did not go', ' to school yesterday.', 'not go'),
      gap('Does she ', 'have', ' a car?', 'base verb'), gap('Did they ', 'finish', ' the project?', 'base verb'),
      gap('My brother doesn’t ', 'watch', ' TV often.', 'base verb'), gap('Why did you ', 'leave', ' early?', 'base verb'),
    ],
  },
  {
    name: 'Englische Wortstellung', level: 'A2', category: 'Satzbau',
    summary: 'Im englischen Aussagesatz steht das Subjekt normalerweise vor dem Verb. Zeit und Ort folgen häufig später im Satz.',
    structure: 'subject + verb + object + place + time',
    usage: ['Aussagesätze klar strukturieren', 'Häufigkeitsadverbien richtig platzieren', 'Zeit- und Ortsangaben natürlich anordnen'],
    signalWords: ['subject first', 'always before main verb', 'place before time'],
    examples: ['She reads books at home every evening.', 'I always drink tea in the morning.', 'They went to London last week.'],
    exercises: [
      gap('Every day / I / coffee / drink: I ', 'drink coffee', ' every day.', 'subject verb object'),
      gap('She / always / is / late: She ', 'is always', ' late.', 'be + adverb'),
      gap('We / play / on Saturdays / tennis: We ', 'play tennis', ' on Saturdays.', 'verb object time'),
      gap('They / yesterday / went / to the cinema: They ', 'went to the cinema', ' yesterday.', 'place time'),
      gap('My dad / often / cooks / dinner: My dad ', 'often cooks', ' dinner.', 'adverb verb'),
      gap('I / at home / study / in the evening: I ', 'study at home', ' in the evening.', 'place time'),
      gap('She / English / speaks / very well: She ', 'speaks English', ' very well.', 'verb object'),
      gap('We / usually / are / tired: We ', 'are usually', ' tired.', 'be + adverb'),
      gap('Tom / last week / bought / a laptop: Tom ', 'bought a laptop', ' last week.', 'verb object time'),
      gap('They / in the park / meet / every Sunday: They ', 'meet in the park', ' every Sunday.', 'place time'),
    ],
  },
  {
    name: 'Bindewörter für klare Sätze', level: 'A2', category: 'Satzbau',
    summary: 'Bindewörter verbinden Gedanken. Sie zeigen Gründe, Folgen, Gegensätze oder die Reihenfolge von Ereignissen.',
    structure: 'reason: because · result: so · contrast: but/although · sequence: before/after/while',
    usage: ['Gründe und Folgen erklären', 'Gegensätze ausdrücken', 'Sätze zu verständlichen Aussagen verbinden'],
    signalWords: ['because', 'so', 'but', 'although', 'before', 'after', 'while'],
    examples: ['I stayed home because I was ill.', 'It was raining, so we took a taxi.', 'Although she was tired, she worked.'],
    exercises: [
      gap('I stayed home ', 'because', ' I was ill.', 'reason'), gap('It was late, ', 'so', ' we took a taxi.', 'result'),
      gap('He is tired, ', 'but', ' he is working.', 'contrast'), gap('', 'Although', ' it was cold, we went outside.', 'contrast'),
      gap('Wash your hands ', 'before', ' dinner.', 'sequence'), gap('We went for a walk ', 'after', ' lunch.', 'sequence'),
      gap('', 'While', ' I was cooking, Tom called.', 'at the same time'), gap('She smiled ', 'because', ' she was happy.', 'reason'),
      gap('I like tea, ', 'but', ' I don’t like coffee.', 'contrast'), gap('The bus was late, ', 'so', ' I arrived after nine.', 'result'),
    ],
  },
  {
    name: 'Phrasal Verbs im Alltag', level: 'A2', category: 'Wortschatz',
    summary: 'Phrasal Verbs verbinden ein Verb mit einer kleinen Ergänzung und haben oft eine eigene Bedeutung.',
    structure: 'verb + particle: look after, find out, give up',
    usage: ['Häufige Wendungen im Alltag verstehen', 'Trennbare und feste Verbindungen erkennen', 'Natürlicher sprechen'],
    signalWords: ['look after', 'find out', 'give up', 'pick up', 'turn on'],
    examples: ['Can you look after my dog?', 'I need to find out the answer.', 'Please turn on the light.'],
    exercises: [
      gap('Can you ', 'look after', ' my cat?', 'care for'), gap('I need to ', 'find out', ' what happened.', 'discover'),
      gap('Please ', 'turn on', ' the light.', 'switch on'), gap('Don’t ', 'give up', ' now.', 'stop trying'),
      gap('I will ', 'pick up', ' the children at five.', 'collect'), gap('She ', 'ran out of', ' time.', 'no longer have'),
      gap('Please ', 'write down', ' your address.', 'record'), gap('He ', 'looked for', ' his keys.', 'search'),
      gap('We need to ', 'set up', ' a meeting.', 'arrange'), gap('Can you ', 'take off', ' your shoes?', 'remove'),
    ],
  },
  {
    name: 'Englisch auf Reisen', level: 'A2', category: 'Kommunikation',
    summary: 'Mit diesen Wendungen kannst du am Flughafen, im Hotel und unterwegs sicher kommunizieren.',
    structure: 'Could I ...? · I’d like ... · Where can I ...?',
    usage: ['Nach dem Weg fragen', 'Im Hotel einchecken', 'Tickets und Essen bestellen'],
    signalWords: ['reservation', 'platform', 'return ticket', 'check in', 'Could I ...?'],
    examples: ['I have a reservation.', 'Which platform does the train leave from?', 'Could I have the bill, please?'],
    exercises: [
      gap('I have a ', 'reservation', ' under the name Smith.', 'booking'), gap('Which ', 'platform', ' does the train leave from?', 'train area'),
      gap('Could I have a ', 'return ticket', ' to York?', 'ticket there and back'), gap('Where can I ', 'check in', '?', 'register at hotel'),
      gap('Is breakfast ', 'included', ' in the price?', 'part of price'), gap('Could you tell me the ', 'way', ' to the station?', 'direction'),
      gap('I’d like to ', 'book', ' a room for two nights.', 'reserve'), gap('Could I have the ', 'bill', ', please?', 'restaurant check'),
      gap('What time does the bus ', 'leave', '?', 'depart'), gap('Is there a pharmacy ', 'nearby', '?', 'close to here'),
    ],
  },
  {
    name: 'Professionelle E-Mails', level: 'B1', category: 'Kommunikation',
    summary: 'Klare Betreffzeilen, höfliche Bitten und passende Abschlüsse machen englische E-Mails professionell.',
    structure: 'Dear ... · I am writing regarding ... · Kind regards, ...',
    usage: ['E-Mails höflich beginnen', 'Anliegen präzise formulieren', 'Professionell abschließen'],
    signalWords: ['regarding', 'please find attached', 'I would appreciate', 'kind regards'],
    examples: ['I am writing regarding your enquiry.', 'Please find the document attached.', 'I would appreciate your reply.'],
    exercises: [
      gap('Dear ', 'Mr Brown', ',', 'name'), gap('I am writing ', 'regarding', ' your enquiry.', 'about'),
      gap('Please find the document ', 'attached', '.', 'included with email'), gap('I would ', 'appreciate', ' your reply.', 'be grateful for'),
      gap('Could you please ', 'confirm', ' the date?', 'verify'), gap('Thank you for your ', 'patience', '.', 'waiting calmly'),
      gap('I look forward to ', 'hearing from you', '.', 'receiving your reply'), gap('Please do not ', 'hesitate', ' to contact me.', 'feel unsure'),
      gap('Kind ', 'regards', ',', 'email closing'), gap('I apologise ', 'for the delay', '.', 'say sorry'),
    ],
  },
  {
    name: 'Aussprache: W und V', level: 'A1', category: 'Aussprache',
    summary: 'W und V klingen im Englischen unterschiedlich. Bewusstes Hören hilft, wichtige Wörter klar zu unterscheiden.',
    structure: 'w: Lippen runden · v: obere Zähne berühren die Unterlippe',
    usage: ['W und V unterscheiden', 'Häufige Verwechslungen vermeiden', 'Neue Wörter laut nachsprechen'],
    signalWords: ['west/vest', 'wine/vine', 'wet/vet', 'window', 'very'],
    examples: ['We went west.', 'The vet works in the village.', 'This wine is very good.'],
    exercises: [
      gap('„wir“ heißt ', 'we', ', nicht ve.', 'w sound'), gap('„sehr“ heißt ', 'very', ', nicht wery.', 'v sound'),
      gap('„Westen“ heißt ', 'west', ', nicht vest.', 'w sound'), gap('„Weste“ heißt ', 'vest', ', nicht west.', 'v sound'),
      gap('„nass“ heißt ', 'wet', ', nicht vet.', 'w sound'), gap('„Tierarzt“ heißt ', 'vet', ', nicht wet.', 'v sound'),
      gap('„Wein“ heißt ', 'wine', ', nicht vine.', 'w sound'), gap('„Rebe“ heißt ', 'vine', ', nicht wine.', 'v sound'),
      gap('„Fenster“ heißt ', 'window', '.', 'w sound'), gap('„Dorf“ heißt ', 'village', '.', 'v sound'),
    ],
  },
]
