import type { Exercise, Topic } from './data'
import { extendedCatalogTopics } from './catalogExtended'

const gap = (before: string, answer: string, after: string, hint: string): Exercise => ({ before, answer, after, hint })

export const catalogTopics: Topic[] = [
  {
    name: 'Possessive Determiners', level: 'A1', category: 'Pronomen',
    summary: 'Possessivbegleiter zeigen, wem eine Person oder Sache gehört.',
    structure: 'my, your, his, her, its, our, their + Nomen',
    usage: ['Besitz und Zugehörigkeit ausdrücken', 'Stehen immer vor einem Nomen', 'Richten sich nach dem Besitzer'],
    signalWords: ['my', 'your', 'his', 'her', 'its', 'our', 'their'],
    examples: ['This is my book.', 'Their house is new.', 'Emma loves her dog.'],
    exercises: [
      gap('I have a bike. ', 'My', ' bike is blue.', 'I'), gap('Tom has a sister. ', 'His', ' sister is ten.', 'Tom'),
      gap('Mia likes ', 'her', ' new school.', 'Mia'), gap('We live in London. ', 'Our', ' flat is small.', 'we'),
      gap('They visit ', 'their', ' grandparents.', 'they'), gap('You need ', 'your', ' passport.', 'you'),
      gap('The cat drinks ', 'its', ' milk.', 'the cat'), gap('I am doing ', 'my', ' homework.', 'I'),
      gap('Paul washes ', 'his', ' car.', 'Paul'), gap('Anna and Leo love ', 'their', ' garden.', 'Anna and Leo'),
    ],
  },
  {
    name: 'Articles: a, an, the', level: 'A1', category: 'Artikel',
    summary: 'Artikel zeigen, ob ein Nomen allgemein, erstmals oder ganz bestimmt gemeint ist.',
    structure: 'a/an + unbestimmtes Nomen · the + bestimmtes Nomen',
    usage: ['a vor einem Konsonantenlaut', 'an vor einem Vokallaut', 'the für bereits bekannte oder eindeutige Dinge'],
    signalWords: ['a', 'an', 'the'],
    examples: ['I see a dog.', 'She eats an apple.', 'The dog is friendly.'],
    exercises: [
      gap('I need ', 'a', ' pen.', 'a/an/the'), gap('She is eating ', 'an', ' orange.', 'a/an/the'),
      gap('Please close ', 'the', ' door.', 'a/an/the'), gap('He is ', 'an', ' honest man.', 'a/an/the'),
      gap('We saw ', 'a', ' film yesterday.', 'a/an/the'), gap('Look at ', 'the', ' moon!', 'a/an/the'),
      gap('Mia wants ', 'an', ' ice cream.', 'a/an/the'), gap('There is ', 'a', ' book on the table.', 'a/an/the'),
      gap('Can you open ', 'the', ' window?', 'a/an/the'), gap('Leo has ', 'an', ' old bicycle.', 'a/an/the'),
    ],
  },
  {
    name: 'Can and Can’t', level: 'A1', category: 'Modalverben',
    summary: 'Can und can’t drücken Fähigkeiten, Möglichkeiten und Erlaubnisse aus.',
    structure: 'Subjekt + can/can’t + Grundform',
    usage: ['Fähigkeiten beschreiben', 'Um Erlaubnis bitten', 'Möglichkeiten ausdrücken'],
    signalWords: ['can', 'can’t', 'Can I ...?', 'Can you ...?'],
    examples: ['I can swim.', 'She can’t drive.', 'Can I come in?'],
    exercises: [
      gap('I ', 'can', ' speak English.', 'can'), gap('A baby ', 'can’t', ' drive a car.', 'can’t'),
      gap('Can you ', 'help', ' me?', 'help'), gap('She can ', 'play', ' the piano.', 'play'),
      gap('We ', 'can’t', ' see in the dark.', 'can’t'), gap('You can ', 'sit', ' here.', 'sit'),
      gap('Tom can ', 'run', ' very fast.', 'run'), gap('Can I ', 'open', ' the window?', 'open'),
      gap('They ', 'can', ' come tomorrow.', 'can'), gap('My dog can’t ', 'climb', ' trees.', 'climb'),
    ],
  },
  {
    name: 'Going-to Future', level: 'A2', category: 'Zeitformen',
    summary: 'Das Going-to Future wird für Pläne und Vorhersagen mit sichtbaren Anzeichen verwendet.',
    structure: 'am/is/are + going to + Grundform',
    usage: ['Geplante Vorhaben', 'Feste Absichten', 'Vorhersagen aufgrund sichtbarer Anzeichen'],
    signalWords: ['tomorrow', 'next week', 'tonight', 'look!'],
    examples: ['I am going to study.', 'It is going to rain.', 'They are going to travel.'],
    exercises: [
      gap('I ', 'am going to visit', ' London next week.', 'visit'), gap('Look at the clouds! It ', 'is going to rain', '.', 'rain'),
      gap('We ', 'are going to cook', ' tonight.', 'cook'), gap('Mia ', 'is going to buy', ' a new phone.', 'buy'),
      gap('They ', 'are going to play', ' football.', 'play'), gap('He ', 'is going to study', ' medicine.', 'study'),
      gap('You ', 'are going to love', ' this film.', 'love'), gap('I ', 'am going to clean', ' my room.', 'clean'),
      gap('The glass ', 'is going to fall', '!', 'fall'), gap('Our friends ', 'are going to stay', ' with us.', 'stay'),
    ],
  },
  {
    name: 'Present Perfect', level: 'A2', category: 'Zeitformen',
    summary: 'Das Present Perfect verbindet vergangene Ereignisse mit der Gegenwart.',
    structure: 'have/has + past participle',
    usage: ['Erfahrungen ohne genauen Zeitpunkt', 'Gerade abgeschlossene Handlungen', 'Handlungen mit Ergebnis in der Gegenwart'],
    signalWords: ['ever', 'never', 'just', 'already', 'yet', 'since', 'for'],
    examples: ['I have visited York.', 'She has just arrived.', 'We haven’t finished yet.'],
    exercises: [
      gap('I ', 'have finished', ' my homework.', 'finish'), gap('She ', 'has visited', ' Paris twice.', 'visit'),
      gap('We have never ', 'seen', ' this film.', 'see'), gap('Tom ', 'has just arrived', '.', 'just arrive'),
      gap('They ', 'have lived', ' here for five years.', 'live'), gap('Mia hasn’t ', 'called', ' yet.', 'call'),
      gap('Have you ever ', 'eaten', ' sushi?', 'eat'), gap('The train ', 'has already left', '.', 'already leave'),
      gap('I ', 'have known', ' him since 2020.', 'know'), gap('Leo ', 'has lost', ' his keys.', 'lose'),
    ],
  },
  {
    name: 'Adjective Comparison', level: 'A2', category: 'Adjektive',
    summary: 'Mit Komparativ und Superlativ werden Personen und Dinge verglichen.',
    structure: 'short: -er/-est · long: more/most · good: better/best',
    usage: ['Zwei Dinge mit dem Komparativ vergleichen', 'Eine Person oder Sache aus einer Gruppe hervorheben', 'than folgt häufig dem Komparativ'],
    signalWords: ['than', 'the ...-est', 'more', 'most'],
    examples: ['Tom is taller than Ben.', 'This book is more interesting.', 'Mia is the best player.'],
    exercises: [
      gap('My car is ', 'faster', ' than yours.', 'fast'), gap('This is the ', 'biggest', ' room.', 'big'),
      gap('English is ', 'easier', ' than I thought.', 'easy'), gap('She is the ', 'best', ' singer here.', 'good'),
      gap('A train is ', 'more comfortable', ' than a bus.', 'comfortable'), gap('Today is ', 'hotter', ' than yesterday.', 'hot'),
      gap('That was the ', 'worst', ' day of my trip.', 'bad'), gap('Leo is ', 'younger', ' than Mia.', 'young'),
      gap('It is the ', 'most expensive', ' hotel.', 'expensive'), gap('This path is ', 'shorter', ' than the other one.', 'short'),
    ],
  },
  {
    name: 'First Conditional', level: 'B1', category: 'Bedingungssätze',
    summary: 'Der First Conditional beschreibt realistische Bedingungen und mögliche Folgen in der Zukunft.',
    structure: 'If + Simple Present, will + Grundform',
    usage: ['Mögliche zukünftige Situationen', 'Warnungen und Versprechen', 'Die Satzteile können ihre Position tauschen'],
    signalWords: ['if', 'unless', 'will'],
    examples: ['If it rains, we will stay home.', 'I will call you if I arrive early.', 'Unless you hurry, you will miss the bus.'],
    exercises: [
      gap('If it rains, we ', 'will stay', ' at home.', 'stay'), gap('She will call if she ', 'arrives', ' early.', 'arrive'),
      gap('If you study, you ', 'will pass', ' the test.', 'pass'), gap('We will miss the bus if we ', 'don’t hurry', '.', 'not hurry'),
      gap('If he ', 'has', ' time, he will help.', 'have'), gap('I ', 'will cook', ' if you buy the food.', 'cook'),
      gap('If they invite us, we ', 'will come', '.', 'come'), gap('You will feel better if you ', 'sleep', '.', 'sleep'),
      gap('If Mia sees Tom, she ', 'will tell', ' him.', 'tell'), gap('Unless it ', 'stops', ' raining, we won’t leave.', 'stop'),
    ],
  },
  {
    name: 'Relative Clauses', level: 'B1', category: 'Satzbau',
    summary: 'Relativsätze geben zusätzliche Informationen zu einer Person, Sache oder einem Ort.',
    structure: 'Person: who · Sache: which/that · Ort: where',
    usage: ['who bezieht sich auf Personen', 'which oder that bezieht sich auf Dinge', 'where bezieht sich auf Orte'],
    signalWords: ['who', 'which', 'that', 'where'],
    examples: ['The woman who lives here is a doctor.', 'This is the book that I bought.', 'York is the city where we met.'],
    exercises: [
      gap('The man ', 'who', ' called is my uncle.', 'Person'), gap('This is the phone ', 'that', ' I lost.', 'Sache'),
      gap('London is the city ', 'where', ' she works.', 'Ort'), gap('The dog ', 'which', ' barked was friendly.', 'Sache'),
      gap('Mia is the girl ', 'who', ' won the race.', 'Person'), gap('I like films ', 'that', ' make me laugh.', 'Sache'),
      gap('That is the café ', 'where', ' we met.', 'Ort'), gap('The teacher ', 'who', ' helps us is new.', 'Person'),
      gap('Here is the letter ', 'which', ' arrived today.', 'Sache'), gap('Do you know the boy ', 'who', ' plays guitar?', 'Person'),
    ],
  },
  {
    name: 'Second Conditional', level: 'B2', category: 'Bedingungssätze',
    summary: 'Der Second Conditional beschreibt hypothetische oder unwahrscheinliche Situationen in Gegenwart und Zukunft.',
    structure: 'If + Simple Past, would + Grundform',
    usage: ['Unwahrscheinliche Zukunftssituationen', 'Hypothetische Wünsche und Ratschläge', 'Were kann bei allen Personen stehen'],
    signalWords: ['if', 'would', 'could', 'were', 'If I were you'],
    examples: ['If I had more time, I would travel.', 'She would help if she knew.', 'If I were you, I would apply.'],
    exercises: [
      gap('If I had more time, I ', 'would learn', ' another language.', 'learn'), gap('She would accept the offer if the salary ', 'were', ' higher.', 'be'),
      gap('If we lived closer, we ', 'could meet', ' more often.', 'can meet'), gap('What would you do if you ', 'lost', ' your passport abroad?', 'lose'),
      gap('If he were more experienced, the company ', 'would hire', ' him.', 'hire'), gap('I ', 'wouldn’t mention', ' it if I were you.', 'not mention'),
      gap('They would reduce costs if they ', 'used', ' less energy.', 'use'), gap('If the weather improved, we ', 'would go', ' hiking.', 'go'),
      gap('Would you move abroad if you ', 'received', ' a good offer?', 'receive'), gap('If Mia knew the answer, she ', 'would tell', ' us.', 'tell'),
    ],
  },
  {
    name: 'Passive Voice', level: 'B2', category: 'Satzbau',
    summary: 'Das Passiv betont eine Handlung oder ihr Ergebnis, während die handelnde Person unwichtig oder unbekannt ist.',
    structure: 'Form von be + past participle · Handelnder optional mit by',
    usage: ['Handlungen und Ergebnisse hervorheben', 'Sachliche und formelle Texte formulieren', 'Den Handelnden auslassen oder mit by ergänzen'],
    signalWords: ['is made', 'was built', 'has been completed', 'will be announced'],
    examples: ['The bridge was built in 1990.', 'The results will be announced tomorrow.', 'The work has been completed.'],
    exercises: [
      gap('The final decision ', 'will be announced', ' tomorrow.', 'announce'), gap('This novel ', 'was written', ' by a Canadian author.', 'write'),
      gap('The documents ', 'have already been sent', ' to all participants.', 'already send'), gap('English ', 'is spoken', ' in many countries.', 'speak'),
      gap('The building ', 'is being renovated', ' at the moment.', 'renovate'), gap('Several mistakes ', 'were found', ' during the review.', 'find'),
      gap('The issue must ', 'be resolved', ' before Friday.', 'resolve'), gap('A new research centre ', 'is going to be opened', ' next year.', 'open'),
      gap('The suspect ', 'was being questioned', ' when the lawyer arrived.', 'question'), gap('By noon, all applications ', 'had been processed', '.', 'process'),
    ],
  },
  ...extendedCatalogTopics,
]
