import type { VocabularyWord } from './vocabularyData'
import { advancedVocabularySets } from './vocabularySetsAdvanced'

export type VocabularySet = {
  id: string
  title: string
  description: string
  level: 'A1' | 'A2' | 'B1' | 'B2'
  words: VocabularyWord[]
}

type WordEntry = [english: string, german: string, description: string, germanDescription?: string]

const createSet = (id: string, title: string, description: string, level: VocabularySet['level'], entries: WordEntry[]): VocabularySet => ({
  id, title, description, level,
  words: entries.map(([english, german, englishDescription, germanDescription], index) => ({
    id: `${id}-${index}`,
    english,
    german,
    englishDescription,
    germanDescription: germanDescription ?? `Gesucht ist die passende englische Übersetzung für „${german}“.`,
    level,
    category: title,
  })),
})

export const vocabularySets: VocabularySet[] = [
  createSet('simple-present', 'Simple Present', 'Routinen, Häufigkeit und wichtige Alltagsverben', 'A1', [
    ['always', 'immer', 'on every occasion or at all times'],
    ['usually', 'normalerweise', 'in the way that most often happens'],
    ['often', 'oft', 'many times or regularly'],
    ['sometimes', 'manchmal', 'on some occasions but not always'],
    ['rarely', 'selten', 'not often'],
    ['never', 'nie', 'not at any time'],
    ['every day', 'jeden Tag', 'on each day'],
    ['morning', 'Morgen', 'the early part of the day'],
    ['evening', 'Abend', 'the later part of the day'],
    ['wake up', 'aufwachen', 'to stop sleeping'],
    ['get up', 'aufstehen', 'to leave your bed after sleeping'],
    ['work', 'arbeiten', 'to do a job'],
    ['study', 'lernen', 'to spend time learning a subject'],
    ['eat', 'essen', 'to put food in your mouth and swallow it'],
    ['drink', 'trinken', 'to take liquid into your mouth'],
    ['go', 'gehen', 'to move or travel to another place'],
    ['play', 'spielen', 'to take part in a game or activity'],
    ['watch', 'anschauen', 'to look at something for a period of time'],
    ['read', 'lesen', 'to understand written words'],
    ['finish', 'beenden', 'to complete an activity'],
  ]),
  createSet('present-progressive', 'Present Progressive', 'Handlungen und Aktivitäten, die gerade stattfinden', 'A1', [
    ['now', 'jetzt', 'at the present moment'],
    ['at the moment', 'im Moment', 'during the present time'],
    ['currently', 'derzeit', 'at the present time'],
    ['look', 'schau', 'used to direct attention to something'],
    ['listen', 'hör zu', 'used to ask someone to pay attention to sound'],
    ['waiting', 'wartend', 'staying until something happens'],
    ['running', 'laufend', 'moving quickly on foot'],
    ['cooking', 'kochend', 'preparing food using heat'],
    ['wearing', 'tragend', 'having clothes on your body'],
    ['sleeping', 'schlafend', 'being in the natural state of rest'],
    ['writing', 'schreibend', 'creating words on paper or a screen'],
    ['talking', 'sprechend', 'having a conversation'],
    ['working', 'arbeitend', 'doing a job or task'],
    ['learning', 'lernend', 'getting new knowledge or skills'],
    ['standing', 'stehend', 'being upright on your feet'],
    ['sitting', 'sitzend', 'resting with your weight on a seat'],
    ['staying', 'bleibend', 'living somewhere for a short time'],
    ['changing', 'sich verändernd', 'becoming different'],
    ['raining', 'regnend', 'when water is falling from clouds'],
    ['happening', 'geschehend', 'taking place now'],
  ]),
  createSet('simple-past', 'Simple Past', 'Vergangene Ereignisse und häufige unregelmäßige Verben', 'A2', [
    ['yesterday', 'gestern', 'the day before today'],
    ['last week', 'letzte Woche', 'the week before the current one'],
    ['ago', 'vor', 'used to say how far back in the past'],
    ['then', 'dann', 'at that time in the past'],
    ['went', 'ging', 'past form of go'],
    ['came', 'kam', 'past form of come'],
    ['saw', 'sah', 'past form of see'],
    ['took', 'nahm', 'past form of take'],
    ['made', 'machte', 'past form of make'],
    ['bought', 'kaufte', 'past form of buy'],
    ['thought', 'dachte', 'past form of think'],
    ['found', 'fand', 'past form of find'],
    ['gave', 'gab', 'past form of give'],
    ['told', 'erzählte', 'past form of tell'],
    ['met', 'traf', 'past form of meet'],
    ['left', 'verließ', 'past form of leave'],
    ['arrived', 'kam an', 'reached a place at the end of a journey'],
    ['visited', 'besuchte', 'went to see a person or place'],
    ['stayed', 'blieb', 'continued to be in a place'],
    ['happened', 'geschah', 'took place in the past'],
  ]),
  createSet('future', 'Future Forms', 'Pläne, Vorhersagen und spontane Entscheidungen', 'A2', [
    ['tomorrow', 'morgen', 'the day after today'],
    ['next week', 'nächste Woche', 'the week after the current one'],
    ['soon', 'bald', 'after a short amount of time'],
    ['later', 'später', 'at a time after now'],
    ['probably', 'wahrscheinlich', 'used when something is likely'],
    ['perhaps', 'vielleicht', 'used when something is possible'],
    ['plan', 'Plan', 'a set of actions you intend to do'],
    ['intention', 'Absicht', 'something you plan to do'],
    ['prediction', 'Vorhersage', 'a statement about what may happen'],
    ['promise', 'Versprechen', 'a statement that you will do something'],
    ['decide', 'entscheiden', 'to choose after thinking'],
    ['expect', 'erwarten', 'to think something will happen'],
    ['hope', 'hoffen', 'to want something to happen'],
    ['travel', 'reisen', 'to go from one place to another'],
    ['visit', 'besuchen', 'to go and see a person or place'],
    ['meet', 'treffen', 'to come together with someone'],
    ['will', 'werden', 'a modal verb used for future events'],
    ['going to', 'vorhaben', 'used for plans and visible predictions'],
    ['in the future', 'in Zukunft', 'at a time that has not happened yet'],
    ['one day', 'eines Tages', 'at an unspecified future time'],
  ]),
  createSet('pronouns', 'Pronouns and Articles', 'Pronomen, Besitz und wichtige Artikel', 'A1', [
    ['I', 'ich', 'the subject pronoun a speaker uses for themselves', 'Personalpronomen als Subjekt: die sprechende Person, Einzahl.'],
    ['you', 'du / ihr / Sie', 'the subject or object pronoun for the person spoken to', 'Personalpronomen für direkt angesprochene Personen, Einzahl oder Mehrzahl.'],
    ['he', 'er', 'a subject pronoun for one male person', 'Personalpronomen als Subjekt: männliche Person, Einzahl.'],
    ['she', 'sie', 'a subject pronoun for one female person', 'Personalpronomen als Subjekt: weibliche Person, Einzahl.'],
    ['it', 'es', 'a subject or object pronoun for one thing or animal', 'Personalpronomen für eine Sache oder ein Tier, Einzahl.'],
    ['we', 'wir', 'a subject pronoun for the speaker and other people', 'Personalpronomen als Subjekt: Sprecher und weitere Personen, Mehrzahl.'],
    ['they', 'sie', 'a subject pronoun for several people or things', 'Personalpronomen als Subjekt: mehrere Personen oder Dinge, Mehrzahl.'],
    ['me', 'mich / mir', 'the object form of I', 'Personalpronomen als Objekt: erste Person, Einzahl.'],
    ['him', 'ihn / ihm', 'the object form of he', 'Personalpronomen als Objekt: männliche Person, Einzahl.'],
    ['her', 'sie / ihr', 'the object form of she', 'Personalpronomen als Objekt: weibliche Person, Einzahl.'],
    ['us', 'uns', 'the object form of we', 'Personalpronomen als Objekt: erste Person, Mehrzahl.'],
    ['them', 'sie / ihnen', 'the object form of they', 'Personalpronomen als Objekt: mehrere Personen oder Dinge.'],
    ['my', 'mein', 'showing that something belongs to me', 'Possessivbegleiter vor einem Nomen: gehört mir.'],
    ['your', 'dein / euer / Ihr', 'showing that something belongs to you', 'Possessivbegleiter vor einem Nomen: gehört der angesprochenen Person.'],
    ['his', 'sein', 'showing that something belongs to him', 'Possessivbegleiter: Besitzer ist männlich und Einzahl.'],
    ['our', 'unser', 'showing that something belongs to us', 'Possessivbegleiter: gehört uns.'],
    ['their', 'ihr', 'showing that something belongs to them', 'Possessivbegleiter: Besitzer sind mehrere Personen.'],
    ['a', 'ein / eine', 'an indefinite article before a consonant sound', 'Unbestimmter Artikel vor einem Konsonantenlaut, zum Beispiel „a book“.'],
    ['an', 'ein / eine', 'an indefinite article before a vowel sound', 'Unbestimmter Artikel vor einem Vokallaut, zum Beispiel „an apple“.'],
    ['the', 'der / die / das', 'the definite article for a specific thing', 'Bestimmter Artikel für eine bekannte oder eindeutig bestimmte Sache.'],
  ]),
  createSet('prepositions', 'Prepositions', 'Zeit- und Ortspräpositionen aus dem Themenkatalog', 'A2', [
    ['at', 'an / um / bei', 'used for exact times and specific points'],
    ['in', 'in', 'used inside a place or with months and years'],
    ['on', 'auf / am', 'used on a surface or with days and dates'],
    ['since', 'seit', 'from a starting point until now'],
    ['for', 'seit / für', 'during a period of time'],
    ['until', 'bis', 'up to a particular time'],
    ['from', 'von / aus', 'showing the starting point'],
    ['to', 'zu / nach', 'showing direction or an end point'],
    ['under', 'unter', 'in a lower position than something'],
    ['above', 'über', 'in a higher position than something'],
    ['between', 'zwischen', 'in the space separating two things'],
    ['behind', 'hinter', 'at the back of something'],
    ['in front of', 'vor', 'in a position ahead of something'],
    ['next to', 'neben', 'at the side of something'],
    ['opposite', 'gegenüber', 'on the other side from something'],
    ['near', 'nahe', 'not far away'],
    ['through', 'durch', 'from one side or end to another'],
    ['across', 'über / quer durch', 'from one side to the other'],
    ['during', 'während', 'at some time within a period'],
    ['before', 'vor', 'earlier than a particular time'],
  ]),
  createSet('everyday-objects', 'Everyday Objects', 'Möbel und häufige Gegenstände aus dem Alltag', 'A1', [
    ['chair', 'Stuhl', 'a piece of furniture for one person to sit on'],
    ['table', 'Tisch', 'furniture with a flat top supported by legs'],
    ['desk', 'Schreibtisch', 'a table used for working or studying'],
    ['bed', 'Bett', 'furniture used for sleeping'],
    ['wardrobe', 'Kleiderschrank', 'a tall cupboard used for storing clothes'],
    ['shelf', 'Regal', 'a flat surface used for holding objects'],
    ['lamp', 'Lampe', 'a device that produces light'],
    ['door', 'Tür', 'a movable barrier used to enter a room'],
    ['window', 'Fenster', 'an opening with glass that lets in light'],
    ['key', 'Schlüssel', 'a small metal object used to open a lock'],
    ['cup', 'Tasse', 'a small container used for drinking'],
    ['plate', 'Teller', 'a flat dish used for serving food'],
    ['bottle', 'Flasche', 'a container with a narrow top for liquids'],
    ['spoon', 'Löffel', 'a tool with a small bowl used for eating'],
    ['knife', 'Messer', 'a tool with a sharp blade used for cutting'],
    ['towel', 'Handtuch', 'a piece of cloth used for drying'],
    ['mirror', 'Spiegel', 'a surface that shows your reflection'],
    ['bag', 'Tasche', 'a container used for carrying things'],
    ['phone', 'Telefon', 'a device used to call and communicate'],
    ['clock', 'Uhr', 'a device that shows the time'],
  ]),
  createSet('general', 'General Vocabulary', 'Nützlicher Wortschatz für Alltag, Lernen und Arbeit', 'B1', [
    ['achieve', 'erreichen', 'to succeed after making an effort'],
    ['advice', 'Rat', 'an opinion that helps someone decide'],
    ['although', 'obwohl', 'used to introduce a surprising contrast'],
    ['appointment', 'Termin', 'an arranged time to meet someone'],
    ['available', 'verfügbar', 'ready to be used or contacted'],
    ['borrow', 'ausleihen', 'to take something and return it later'],
    ['challenge', 'Herausforderung', 'a difficult task that tests ability'],
    ['comfortable', 'bequem', 'making you feel physically relaxed'],
    ['decision', 'Entscheidung', 'a choice made after thinking'],
    ['environment', 'Umwelt', 'the natural world around us'],
    ['experience', 'Erfahrung', 'knowledge gained by doing something'],
    ['improve', 'verbessern', 'to make or become better'],
    ['journey', 'Reise', 'travelling from one place to another'],
    ['neighbour', 'Nachbar', 'a person who lives near you'],
    ['opportunity', 'Gelegenheit', 'a situation that makes something possible'],
    ['reliable', 'zuverlässig', 'able to be trusted'],
    ['require', 'erfordern', 'to need or make something necessary'],
    ['schedule', 'Zeitplan', 'a plan showing when activities happen'],
    ['suitable', 'geeignet', 'right for a particular purpose'],
    ['probably', 'wahrscheinlich', 'used when something is likely'],
  ]),
  ...advancedVocabularySets,
]
